import CarouselContainer from '@/common/components/ui/carousel/CarouseContainer';
import Categories from '@/common/components/ui/categories/Categories';
import Header from '@/common/components/ui/Header';
import apiProductos from '@/services/resources/products';
import { Box, Container } from '@mui/material';

import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';

export interface CategoryType {
  slug: string
  name: string
  url: string
}

export default function Home() {
  const [category, setCategory] = useState<CategoryType[]>([]);
  const [loading, setLoading] = useState<boolean>(false);

  const router = useRouter();

  useEffect(() => {
    setLoading(true)
    apiProductos
      .getAllCategory().then((response) => {
        console.log(response);
        setCategory(response)
      }).finally(() => {
        setLoading(false)
      })
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container>
        <Box sx={{ position: 'relative' }}>
          <Box sx={{ position: 'relative', zIndex: 1 }}>
            <CarouselContainer />
          </Box>
          <Box
            sx={{
              position: 'absolute',
              top: 0,
              left: 0,
              zIndex: 1,
              marginTop: '230px',
              width: '100%',
            }}
          >
            <Categories
              category={category}
              loading={loading}
              onClickItem={(slug) => {
                router.push(`/productos/categoria/${slug}`)
              }}
            />
          </Box>
        </Box>
      </Container>
    </>
  );
}
