import Header from '@/common/components/ui/Header'
import Head from 'next/head'

// const categoryImages = {
//   beauty: '',
//   furniture: ''
// }

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div>Pagina principal</div>
    </>
  )
}
